sim_dt: 0.25
env_xlim: [0, 0.5]
env_ylim: [0, 0.5]
tree_size: 1000
rollout_horizon: 1000
c_param: 1.4
goal: [0.25, 0.25]
num_nodes_A: 1 # number of attackers
num_nodes_B: 1 # number of defenders
robots:
- acceleration_limit: 0.125
  speed_limit: 0.125
  tag_radius: 0.025
  r_sense: 1.0
  x0: [0.05,0.25,0,0]
- acceleration_limit: 0.125
  speed_limit: 0.125
  tag_radius: 0.025
  r_sense: 1.0
  x0: [0.35,0.25,0,0]
# seed: 10